version: '3'

networks:
    frontend:
        driver: ${NETWORKS_DRIVER}
    backend:
        driver: ${NETWORKS_DRIVER}

volumes:
    mysql:
        driver: ${VOLUMES_DRIVER}


services:
    workspace:
        build:
            context: "${WORKSPACE_PATH}"
            args:
                - WS_OS=${WS_OS}
                - PHP_VER=${PHP_VER}
        volumes:
            - "${WORKSPACE_PATH}:/var/www"
        tty: true
        networks:
            - frontend
            - backend
    mysql:
        build:
            context: "${MYSQL_PATH}"
            args:
                - MYSQL_VER_DOT=${MYSQL_VER_DOT}
                - MYSQL_VER=${MYSQL_VER}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_TZ=${MYSQL_TZ}
        volumes:
            - ${DATA_PATH}/mysql:/var/lib/mysql
            - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
            - ${LOG_PATH}/mysql:/var/log/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        depends_on:
            - workspace
        networks:
            - backend
    php: 
        image: php:${PHP_IMAGE}
        volumes:
            - ${WORKSPACE_PATH}:${APP_CODE_PATH_CONTAINER}
        depends_on:
            - workspace
        networks:
            - backend
    nginx: ## laradock
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
                - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
                - CHANGE_SOURCE=${CHANGE_SOURCE}
                - http_proxy
                - https_proxy
                - no_proxy
        volumes:
            - ${WORKSPACE_PATH}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php
        networks:
            - frontend
            - backend
